### PR TITLE
Work around permission denied on /dev/stderr

### PR DESCRIPTION
**Pull request by oyvinev**
Fix for the same error described in #3, except for /dev/stderr.

### CODE REVIEW

**Comment by livibetter** [comment]
@oyvinev thanks for the PRs (#7), but I haven't read anything since I am not actually maintaining anything in @lbarchive.  So, I'd like to ask you if you are interested in taking over log.sh?

If you do, I will transfer this over to your account, then you can handle these two on your own.

**Comment by oyvinev** [comment]
I can't promise much maintenance myself, but since I'm actually using it (and liking it!) you never know. So yes, feel free to transfer it to my account.

**Comment by livibetter** [comment]
@oyvinev "oyvinev already has a repository in the lbarchive/log.sh network and You can only transfer a repository from an organization to yourself at this time "

So you have to delete your repo on GitHub first.

**Comment by oyvinev** [comment]
Deleted now.

**Comment by livibetter** [comment]
@oyvinev I had to transfer this repo back to my user account, so that I could make a transfer request, which should be in your mailbox.

**Comment by oyvinev** [comment]
Thanks.

**Pull request merged**
